spring:
  application:
    name: LoanTrackr
  config:
    import: classpath:application-secret.yml
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: ${REDIS_DATABASE_PORT}
      host: ${REDIS_DATABASE_HOST}
      connect-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 3000
          timeout: 5000
          write timeout: 5000
          from: no-reply@loantrackr.com
          pool: true
          size: 5
    protocol: smtp
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: 900000
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
file:
  upload-dir: uploads
mail:
  from:
    email: no-reply@loantrackr.com
    name: LoanTrackr Team
bootstrap:
  email: ${BOOTSTRAP_EMAIL}